baseURL: http://codewithflavor.com/
languageCode: en-us
title: "Code With Flavor"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Code With Flavor"
  description: "Learn programming with a dash o cooking"
  keywords: [Blog, Programming, Cooking, CSharp, .NET, Microsoft]
  author: "Jan Kliszcz"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  assets:
        disableFingerprinting: true
  
  customCss: ["/style.css"]

  label:
    iconSVG: <svg xmlns="http://www.w3.org/2000/svg"   viewBox="0 0 323.25 162" height="30" version="1.0"><path d="M83.555 5.746c0 1.16-.407 2.149-1.223 2.969l-72.23 72.7 72.23 72.702a4.23 4.23 0 0 1 .98 1.363 4.186 4.186 0 0 1 .368 1.641 4.202 4.202 0 0 1-3.434 4.223c-.277.05-.558.07-.84.066a4.295 4.295 0 0 1-1.636-.375 4.092 4.092 0 0 1-1.356-.984L1.227 84.383a4.298 4.298 0 0 1-.52-.637 4.438 4.438 0 0 1-.383-.726 4.112 4.112 0 0 1-.316-1.605 4.1 4.1 0 0 1 .316-1.606c.106-.254.235-.496.383-.727.152-.227.328-.441.52-.633L76.414 2.781c.293-.293.621-.539.984-.734.368-.195.75-.332 1.157-.414a4.037 4.037 0 0 1 1.226-.059 4.159 4.159 0 0 1 2.238.93 4.191 4.191 0 0 1 1.536 3.242Zm0 0" /><path d="M239.695 156.242c0-1.156.407-2.148 1.223-2.969l72.23-72.699-72.23-72.699a4.101 4.101 0 0 1-.559-.633 4.416 4.416 0 0 1-.422-.734 4.098 4.098 0 0 1-.265-.801 4.047 4.047 0 0 1-.102-.84 4.099 4.099 0 0 1 .067-.844 4.128 4.128 0 0 1 .629-1.559c.152-.237.332-.456.53-.655a4.11 4.11 0 0 1 1.398-.926 4.165 4.165 0 0 1 3.286.07c.254.117.5.258.727.422.23.168.438.355.629.563l75.187 75.667c.192.196.368.41.52.637.148.23.277.473.383.727a4.184 4.184 0 0 1 .316 1.605 4.14 4.14 0 0 1-.316 1.606 4.603 4.603 0 0 1-.383.726c-.152.23-.328.442-.52.637l-75.187 75.668a4.185 4.185 0 0 1-3.367 1.207 4.18 4.18 0 0 1-2.239-.934 4.171 4.171 0 0 1-.828-.91 4.393 4.393 0 0 1-.523-1.113 4.17 4.17 0 0 1-.184-1.219Zm0 0" /><path d="M160.824 50.297c-.68-6.004-6.183-9.774-6.418-9.93a2.161 2.161 0 0 0-2.41 3.586c.043.031 4.086 2.856 4.535 6.832.262 2.29-.734 4.656-2.96 7.035-2.891 3.094-4.169 6.465-3.798 10.016.715 6.828 7.438 11.602 7.723 11.8.379.262.805.391 1.234.391.68 0 1.348-.324 1.77-.922a2.169 2.169 0 0 0-.527-3.011c-.055-.04-5.407-3.871-5.907-8.727-.234-2.273.637-4.43 2.66-6.594 3.13-3.347 4.508-6.87 4.098-10.476M128.621 64.758c.899 8.586 9.406 14.625 9.77 14.879a2.147 2.147 0 0 0 3-.532c.687-.98.449-2.328-.524-3.011-.074-.055-7.273-5.192-7.953-11.805-.32-3.11.902-6.168 3.625-9.082 3.934-4.207 5.672-8.617 5.16-13.11-.851-7.507-7.765-12.245-8.062-12.44a2.157 2.157 0 0 0-2.992.581 2.173 2.173 0 0 0 .578 3.004c.054.035 5.578 3.86 6.187 9.371.352 3.164-1.004 6.407-4.023 9.637-3.625 3.879-5.23 8.086-4.766 12.508M104.969 60.758c1.136 10.87 11.965 18.558 12.426 18.879.375.261.804.39 1.234.39.68 0 1.348-.324 1.77-.922a2.165 2.165 0 0 0-.532-3.011c-.097-.07-9.683-6.906-10.605-15.801-.438-4.246 1.207-8.39 4.883-12.328 4.98-5.324 7.18-10.883 6.539-16.524-1.075-9.464-9.825-15.46-10.2-15.71a2.157 2.157 0 0 0-2.992.585 2.164 2.164 0 0 0 .578 3c.078.051 7.493 5.172 8.325 12.641.48 4.313-1.336 8.707-5.399 13.055-4.582 4.898-6.61 10.195-6.027 15.746" /><path d="M231.512 99.84c0 3.715-3.016 6.734-6.727 6.734h-7.238V92.926h7.238c3.711 0 6.727 3.02 6.727 6.734Zm-18.285 38.86c0 10.37-8.43 18.808-18.786 18.808h-65.828c-10.36 0-18.785-8.438-18.785-18.809V92.926h103.399ZM98.27 106.573c-3.707 0-6.727-3.02-6.727-6.734v-.18c0-3.715 3.02-6.734 6.727-6.734h7.238v13.648Zm126.515-17.972H98.27c-6.09 0-11.047 4.96-11.047 11.058v.18c0 6.097 4.957 11.062 11.047 11.062h7.238V138.7c0 12.754 10.367 23.133 23.105 23.133h65.828c12.739 0 23.106-10.379 23.106-23.133v-27.797h7.238c6.09 0 11.047-4.965 11.047-11.062v-.18c0-6.097-4.957-11.058-11.047-11.058" /><path d="M199.453 28.832c21.078 22.04 21.137 42.719 19.918 51.445L148.984 6.684c8.746-.84 29.391.105 50.47 22.148Zm-3.281-10.86a9.888 9.888 0 0 1 7.121-2.773 9.917 9.917 0 0 1 6.996 3.082l.164.176c3.805 3.98 3.668 10.316-.305 14.125l-.972.934a94.143 94.143 0 0 0-6.602-7.676 95.023 95.023 0 0 0-7.37-6.938Zm21.914 67.212a2.975 2.975 0 0 0 5.059-1.426c1.285-5.965 3.636-24.965-11.395-46.723l1.387-1.328c5.691-5.46 5.89-14.543.433-20.246l-.168-.172a14.179 14.179 0 0 0-10.015-4.414 14.308 14.308 0 0 0-10.2 3.973l-1.386 1.328C170.738.199 151.67 1.723 145.67 2.758a2.973 2.973 0 0 0-2.32 2 2.987 2.987 0 0 0 .68 3l74.055 77.426" /></svg>

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false

  homeInfoParams:
    Title: "Code With Flavor üíªüçΩÔ∏è"
    Content: "Learn programming with a dash of cooking lessons"

  socialIcons:
    - name: "facebook"
      url: "https://www.facebook.com/codewithflavor" 
    - name: "instagram"
      url: "https://www.instagram.com/codewithflavor/"
    - name: "github"
      url: "https://github.com/janex-PL"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jan-kliszcz/"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about-me
      name: "About Me"
      url: /about-me/
      weight: 10
    - identifier: search
      name: "Search"
      url: /search/
      weight: 20
    - identifier: categories
      name: "Categories"
      url: /categories/
      weight: 30
    
taxonomies:
  category: categories
  tag: tags
